# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/frameworks-getting-started',
                'doc_host': 'https://nd-crane.github.io',
                'git_url': 'https://github.com/nd-crane/frameworks-getting-started',
                'lib_path': 'frameworks_getting_started'},
  'syms': { 'frameworks_getting_started.core': { 'frameworks_getting_started.core.foo': ( 'core.html#foo',
                                                                                          'frameworks_getting_started/core.py')}}}
